# chats/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from . import views

# Create a router and register our viewsets
router = DefaultRouter()
router.register(r'conversations', views.ConversationViewSet, basename='conversation')
router.register(r'messages', views.MessageViewSet, basename='message')
router.register(r'users', views.UserViewSet, basename='user')

# Define URL patterns
urlpatterns = [
    # Include the router URLs
    path('api/', include(router.urls)),
    
    # Additional function-based view endpoints
    path('api/stats/', views.conversation_stats, name='conversation-stats'),
    path('api/recent/', views.recent_conversations, name='recent-conversations'),
]

# URL patterns generated by the router:
"""
Conversation endpoints:
- GET    /api/conversations/                    - List all conversations
- POST   /api/conversations/                    - Create new conversation
- GET    /api/conversations/{id}/               - Get specific conversation with messages
- PUT    /api/conversations/{id}/               - Update conversation
- PATCH  /api/conversations/{id}/               - Partially update conversation
- DELETE /api/conversations/{id}/               - Delete conversation
- POST   /api/conversations/{id}/add_participant/    - Add participant to conversation
- POST   /api/conversations/{id}/remove_participant/ - Remove participant from conversation
- PATCH  /api/conversations/{id}/update_title/       - Update conversation title
- GET    /api/conversations/{id}/participants/       - Get conversation participants
- GET    /api/conversations/search/                  - Search conversations

Message endpoints:
- GET    /api/messages/                         - List messages (with ?conversation_id=)
- POST   /api/messages/                         - Create new message
- GET    /api/messages/{id}/                    - Get specific message
- PUT    /api/messages/{id}/                    - Update message
- PATCH  /api/messages/{id}/                    - Partially update message
- DELETE /api/messages/{id}/                    - Delete message
- POST   /api/messages/mark_as_read/            - Mark messages as read
- GET    /api/messages/{id}/replies/            - Get replies to message
- GET    /api/messages/search/                  - Search messages
- GET    /api/messages/unread/                  - Get unread messages

User endpoints:
- GET    /api/users/                            - List users
- GET    /api/users/{id}/                       - Get specific user
- GET    /api/users/search/                     - Search users
- GET    /api/users/online/                     - Get online users

Additional endpoints:
- GET    /api/stats/                            - Get conversation statistics
- GET    /api/recent/                           - Get recent conversations
"""